spring:
  application:
    name: edrive-backend
  datasource:
    url: jdbc:mysql://localhost:3306/edrive
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

# In minutes
security:
  jwt:
    access-token-secret: 218ff189baacccb10e29d4f7ab95cc2a629f9981e486f3a27e9b7028eb75d1e1
    refresh-token-secret: 543db37a5970ea4769401536da421e294f03cecc43dc1b2e6c6c12c16aa88981
    access-token-duration: 10
    refresh-token-duration: 10080

encryption:
  rsa-key-size: 4096
  aes-key-size: 256
  gcm-tag-size: 128
  iv-size: 96
  algorithm: AES/GCM/NoPadding
  chunk-size: 4096

certificate:
  main:
    path: certs/main/cert.pem
    key-path: certs/main/key.pem
    duration: 3650
    issuer:
      common-name: Singidunum CA
      org-unit: ZIS
      org: Singidunum
      locality: Belgrade
      state: RS
      country: RS

  inter:
    path: certs/inter/cert.pem
    key-path: certs/inter/key.pem
    duration: 365
    issuer:
      common-name: Singidunum Intermediate
      org-unit: ZIS
      org: Singidunum
      locality: Belgrade
      state: RS
      country: RS